id: I098DDD06
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T07:21:45+00:00'
last_modified: '2022-06-08T01:06:43.936434+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18526
  title: དུག་ནད་གསོ་བ། བཅོས་སྒྲིག་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    7CCB:
      image_group_id: I8LS18528
      title: ''
      total_pages: 140
      order: 1
      base_file: 7CCB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
